services:
    app.twig.screenshotlayer:
        class:     AppBundle\Twig\ScreenshotlayerExtension
        arguments:  ['%screenshotlayerApiKey%']
        tags:
            - { name: twig.extension }  
  
